### ISSUE TITLE
Can't "update" playlists?

### ISSUE THREAD

**Issue by Tadiian** [Metalit/PlaylistDownloader#1]
I downloaded a playlist. Later added a few more songs to it. Is there no way to update it and download the new songs?  
The buttons do download are greyed out. Can't find a way to download the new songs.

**Comment by Metalit** [comment]
Syncing playlists after download is primarily a feature of playlist manager, which will be coming soon. I'll consider adding a way to update playlists with playlist downloader as well, but it's a little difficult to tell if it's the same playlist in that case

**Comment by jLynx** [comment]
+1 for this feature too. Since the manager is no here yet, I have to manually delete the playlist and re downloads it with with. Would be great if instead of disabling the buttons, it changed to sync or update to re download all the missing songs

**Comment by Metalit** [comment]
Feature added!
